[env:nano_im16]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags = -D ROBOT_IM_16

[env:nano_codex8]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags = -D ROBOT_CODEX_8
