[env:nano_im16]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags = -D ROBOT_IM_16
build_src_filter = +<main.cpp>

[env:nano_codex8]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
upload_speed = 115200
build_flags = -D ROBOT_CODEX_8
build_src_filter = +<main.cpp>

[env:esp32_bt_car]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 460800
build_src_filter = +<esp32_bt_car.cpp>
